export const mockProducts = [
  {
    id: '1',
    name: 'Süt 1L',
    store: 'A101 Saadetdere',
    distance: '0.3km',
    originalPrice: 25,
    discountedPrice: 15,
    discountPercent: 40,
    expiryDate: '01.04.2026',
    daysLeft: 0,
    stock: 10,
    category: 'Süt & Süt Ürünleri',
    emoji: '🥛',
    latitude: 41.0082,
    longitude: 28.9784,
  },
  {
    id: '2',
    name: 'Ekmek',
    store: 'BİM Bahçeyolu',
    distance: '0.8km',
    originalPrice: 10,
    discountedPrice: 5,
    discountPercent: 50,
    expiryDate: '01.04.2026',
    daysLeft: 0,
    stock: 20,
    category: 'Ekmek & Unlu',
    emoji: '🍞',
    latitude: 41.0092,
    longitude: 28.9794,
  },
  {
    id: '3',
    name: 'Yoğurt 500g',
    store: 'ŞOK Üç Evler',
    distance: '1.2km',
    originalPrice: 30,
    discountedPrice: 20,
    discountPercent: 33,
    expiryDate: '01.04.2026',
    daysLeft: 0,
    stock: 5,
    category: 'Süt & Süt Ürünleri',
    emoji: '🥗',
    latitude: 41.0102,
    longitude: 28.9804,
  },
  {
    id: '4',
    name: 'Tavuk Göğsü 500g',
    store: 'ŞOK Üç Evler',
    distance: '1.2km',
    originalPrice: 70,
    discountedPrice: 45,
    discountPercent: 35,
    expiryDate: '04.04.2026',
    daysLeft: 3,
    stock: 8,
    category: 'Et & Tavuk',
    emoji: '🥩',
    latitude: 41.0102,
    longitude: 28.9804,
  },
  {
    id: '5',
    name: 'Meyve Suyu 1L',
    store: 'A101 Saadetdere',
    distance: '0.3km',
    originalPrice: 28,
    discountedPrice: 18,
    discountPercent: 35,
    expiryDate: '06.04.2026',
    daysLeft: 5,
    stock: 15,
    category: 'İçecek',
    emoji: '🥤',
    latitude: 41.0082,
    longitude: 28.9784,
  },
  {
    id: '6',
    name: 'Kaşar Peyniri 200g',
    store: 'Migros Esenyurt',
    distance: '1.5km',
    originalPrice: 55,
    discountedPrice: 32,
    discountPercent: 40,
    expiryDate: '01.04.2026',
    daysLeft: 0,
    stock: 3,
    category: 'Süt & Süt Ürünleri',
    emoji: '🧀',
    latitude: 41.0112,
    longitude: 28.9814,
  },
];

export const mockNotifications = [
  {
    id: '1',
    title: 'Fırsat Kaçıyor!',
    body: "A101 Saadetdere'de Süt 1L %40 indirimle sadece ₺15!",
    tag: '🥛 Süt & Süt Ürünleri',
    time: '5 dk',
    unread: true,
    urgent: false,
    emoji: '💥',
  },
  {
    id: '2',
    title: 'Son Gün!',
    body: "BİM Bahçeyolu'nda Ekmek %50 indirimle sadece ₺5!",
    tag: '🔥 Bugün bitiyor',
    time: '1 sa',
    unread: true,
    urgent: true,
    emoji: '🚨',
  },
  {
    id: '3',
    title: 'Yeni İndirim',
    body: "ŞOK Üç Evler'de Tavuk Göğsü %35 indirimle ₺45!",
    tag: '🥩 Et & Tavuk',
    time: '3 sa',
    unread: true,
    urgent: false,
    emoji: '🎉',
  },
  {
    id: '4',
    title: 'Rezervasyonun Onaylandı',
    body: "Süt 1L rezervasyonun A101 Saadetdere tarafından onaylandı.",
    tag: '✅ Rezervasyon',
    time: 'Dün',
    unread: false,
    urgent: false,
    emoji: '✅',
  },
];

export const mockStores = [
  {
    id: '1',
    name: 'A101 Saadetdere',
    distance: '0.3km',
    hours: '07:00 – 22:00',
    productCount: 5,
    urgentCount: 2,
    emoji: '🏪',
    latitude: 41.0082,
    longitude: 28.9784,
  },
  {
    id: '2',
    name: 'BİM Bahçeyolu',
    distance: '0.8km',
    hours: '07:30 – 22:00',
    productCount: 3,
    maxDiscount: 50,
    emoji: '🏬',
    latitude: 41.0092,
    longitude: 28.9794,
  },
  {
    id: '3',
    name: 'ŞOK Üç Evler',
    distance: '1.2km',
    hours: '08:00 – 22:00',
    productCount: 4,
    urgentCount: 1,
    emoji: '🏪',
    latitude: 41.0102,
    longitude: 28.9804,
  },
];

export const mockReservations = [
  {
    id: '1',
    product: mockProducts[0],
    status: 'active',
    reservedAt: '09:30',
    expiresAt: '12:30',
    code: 'CPK-1234',
  },
  {
    id: '2',
    product: mockProducts[3],
    status: 'completed',
    reservedAt: 'Dün 14:00',
    expiresAt: 'Dün 17:00',
    code: 'CPK-1198',
  },
];

export const mockUser = {
  name: 'Ayşe Kaya',
  email: 'ayse@gmail.com',
  emoji: '👩',
  totalShopping: 47,
  totalSaving: 312,
  savedKg: 18,
  points: 485,
};